/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cha9or.gltf 
Author: Vaxatron (https://sketchfab.com/Vaxatron)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/punisher-meat-cleaver-c97765eb479645c28cabd90e5827376b
Title: PUNISHER Meat Cleaver
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cha9or.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Knife_Low_Res02__0.geometry} material={materials['Scene_-_Root']} />
    </group>
  )
}

useGLTF.preload('/cha9or.gltf')
