/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cleaver.gltf 
Author: 3dsofsan (https://sketchfab.com/3dsofsan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cleaver-butchers-best-friend-8b3a394b1e6741e187e15b8dc5075b54
Title: Cleaver - Butcher's Best Friend
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cleaver.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.566}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[0, 0, 0.611]}>
            <mesh geometry={nodes.Cleaver__cleaver01___Default_0.geometry} material={materials.cleaver01___Default} position={[0.423, 0.604, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cleaver.gltf')
